config/routes.rb
Rails.application.routes.draw do
  resources :websites
  devise_for :users
  root "websites#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_and_belongs_to_many :websites

# roles
 SYSTEMADMIN = "0"
 ADMIN = "1"
 WORKER = "2"

 def website
   websites.find_by_id(current_website)
 end

 def website=(website=Website.new)
   self.current_website = website.id
 end

end

app/models/website.rb
class Website < ApplicationRecord
  has_and_belongs_to_many :users
  validates :users, length: { :minimum => 1 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.fetch(:test, {})
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = current_user.websites
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    respond_to do |format|
      format.html { redirect_to edit_website_path(@website)  }
      format.json { render :show }
    end
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)
    @website.users << current_user

    respond_to do |format|
      if @website.save
        current_user.website = @website
        current_user.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:name, :domain, :name_servers, :online, :published_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/_main_pannel.html.erb
<div class="main-pannel">
  <header><h1><%= yield :title %></h1></header>
  <%= render 'layouts/user_interface_messages' %>
  <main>
    <div class="breadcrumbs">
      <%= yield :breadcrumbs %>
    </div>
    <div class="buttons row">
      <%= yield :buttons %>
    </div>
    <%= yield %>
  </main>
</div>

app/views/layouts/_side_pannel.html.erb
<% if user_signed_in? %>
<div class="side-pannel">

  <div class="logo">
    <img src="/logo.png">
  </div>
  <div class="menu">
    <div class="user-section row">
      <div class="user_information col-xs-8">
        <div class="restaurant_name">שם המסעדה</div>
        <div class="user_email">mail@domain.com</div>
      </div>
      <div class="website-logo col-xs-4">
        <img src="http://2.bp.blogspot.com/-I4Tr_GdLzcs/ULy9kW0Jv1I/AAAAAAAAPg8/S13OoHZ97Rc/s1600/1-restaurant-logo-design.jpg">
      </div>
      <div class="log-out">
        <%= link_to "התנתק", destroy_user_session_path, method: :delete %>
      </div>
    </div>
    <div class="links">
        <% 4.times do |number| %>
        <a class="parent">תפריט <%= number+1 %></a>
        <div class="sub-links">
          <% 4.times do |number2| %><a href="/">תת תפריט <%= number2+1 %></a><% end %>
        </div>
        <% end %>
        <a href="/">לינק לדף הבית</a>
    </div>
  </div>
</div>
  <% content_for :foot do %>
  <script>
  $( ".links" ).accordion({
    collapsible: true,
    active: false,
    header: 'a.parent'
  });
  </script>
  <% end %>
<% end %>

app/views/layouts/_user_interface_messages.html.erb
<% if notice.present? || alert.present? %>
<div class="user-interface-messages">
  <% if notice.present? %>
  <div class="notice-message">
    <p><%= notice %></p>
    <a class="close-button"></a>
  </div>
  <% end %>
  <% if alert.present? %>
  <div class="alert-message">
    <p><%= alert %></p>
    <a class="close-button"></a>
  </div>
  <% end %>
  <script>
    $('a.close-button').click(function () {
      $(this).parent().hide(100);
    });
  </script>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bonjo | <%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='http://s3-eu-west-1.amazonaws.com/konimboassets/layout3/base/fonts/open_sans_hebrew/stylesheet.css' type='text/css'>
    <%= yield :head %>
  </head>

  <body>
    <div class="split-screen">
      <%= render 'layouts/side_pannel' %>
      <%= render 'layouts/main_pannel' %>
    </div>
  <%= yield :foot %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymenu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='http://s3-eu-west-1.amazonaws.com/konimboassets/layout3/base/fonts/open_sans_hebrew/stylesheet.css' type='text/css'>
  </head>

  <body>
    <%= render 'layouts/user_interface_messages' %>
    <div class="login">
      <div class="heading">
      <%= yield %>
      <%= render "devise/shared/links" %>
    	</div>
    </div>
  </body>
</html>

app/views/websites/_form.html.erb
<%= form_for(website) do |f| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :domain %>
    <%= f.text_field :domain %>
  </div>

  <div class="field">
    <%= f.label :name_servers %>
    <%= f.text_field :name_servers %>
  </div>

  <div class="field">
    <%= f.label :online %>
    <%= f.check_box :online %>
  </div>

  <div class="field">
    <%= f.label :published_at %>
    <%= f.datetime_select :published_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<% content_for :title do %>
עריכת פרטי האתר
<% end %>
<%= render 'form', website: @website %>

<% content_for :buttons do %>
<%= link_to 'כל האתרים', websites_path %>
<% end %>

app/views/websites/index.html.erb
<% content_for :title do %>
כל האתרים
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Domain</th>
      <th>Name servers</th>
      <th>Online</th>
      <th>Published at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.name %></td>
        <td><%= website.domain %></td>
        <td><%= website.name_servers %></td>
        <td><%= website.online %></td>
        <td><%= website.published_at %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% content_for :buttons do %>
<%= link_to 'אתר חדש', new_website_path %>
<% end %>

app/views/websites/new.html.erb
<% content_for :title do %>
אתר חדש
<% end %>

<%= render 'form', website: @website %>

<% content_for :buttons do %>
<%= link_to 'כל האתרים', websites_path %>
<% end %>

app/views/websites/show.html.erb
unavailable